host-name: 0.0.0.0
transfer-timeout: 800
mongodb: mongodb://mongodb
redis-url: redis://redis:6379
velocity-secret: ixmSUgWOgvs7
require-auth: false
sandbox: false
spark: false
anticheat: false
redis-uri: redis://redis:6379
limbo:
    host-name: nanolimbo
    port: 65535
